import = [
  "~/.config/alacritty/themes/themes/xterm.toml"
]

[shell]
program = "/usr/bin/tmux"
args = ["new-session"]
# Configuration for Alacritty, the GPU enhanced terminal emulator.

[env]
TERM = "xterm-256color"

[font]
# Tamaño de la fuente
#normal.family = "MesloLGS Nerd Font Mono"
#normal.family = "HackNerdFont"
normal.family = "Consolas"

size = 16

[cursor]
style = "Block"

[window]
#padding.x = 10
#padding.y = 10

decorations = "none"

#opacity = 0.7
#blur = true
#option_as_alt = "Both"

startup_mode = "Maximized"

